### ISSUE TITLE
Directory issue

### ISSUE THREAD

**Issue by peterdoherty01** [darshanbaral/mero#1]
Hi - nice theme!

I have trouble deploying to Netlify. Basically, the error log says cannot find the theme:

> Error: Unable to find theme Directory: /opt/build/repo/themes/mero

In github, I notice that it says "mmero". Could this be the problem? If so, where do I fix that?

![image](https://user-images.githubusercontent.com/22255078/54623570-2aed4300-4a42-11e9-8d36-8fa2cd427c45.png)

Thank you

**Comment by peterdoherty01** [comment]
I found a solution. Remove theme="mero" from the config file. Note: I tried using other themes and had the same issue. This was due to something wrong on my side probably.

**Comment by darshanbaral** [comment]
@peter-doherty, sorry I just saw the issue. Glad it got resolved.
